name: emergent
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python>=3.10

  # Core scientific stack
  - numpy>=1.20
  - pandas>=1.3
  - scipy>=1.7
  - matplotlib>=3.4

  # Geospatial libraries
  - geopandas>=0.9
  - shapely>=1.7
  - fiona>=1.8
  - rasterio>=1.2
  - affine>=2.4
  - pyproj>=3.0

  # Data storage and parallel processing
  - h5py>=3.1
  - dask>=2021.6

  # GUI and visualization
  - pyqt>=5.15
  - pyqtgraph>=0.12

  # Ocean and atmospheric data
  - xarray>=0.19
  - netcdf4>=1.5
  - h5netcdf>=0.11

  # Network utilities
  - networkx>=2.6
  - requests>=2.25

  # Pip-only dependencies (not in conda-forge or need specific versions)
  - pip
  - pip:
    - fsspec>=2021.8
    - s3fs>=2021.8
    - cfgrib>=0.9.10
    - aiobotocore>=2.0
    - aiohttp>=3.7

  # Development tools (optional)
  # - black>=22.0
  # - isort>=5.0
  # - pytest>=7.0
  # - pytest-cov>=3.0
